### ISSUE TITLE
Definir layout da página web

### ISSUE THREAD

**Issue by mateus4k** [4klabs/portfolio#2]
## Seções do site
- A definir

**Comment by matheuscont** [comment]
Observações para escolha escolha de layout - Matheus
1. Background e estilos globais: 
   a. Cor única de background
   b. Seguir inicialmente todo esquema de cores e fontes do site modelo (ver anexo).
![style portfolio ](https://user-images.githubusercontent.com/103283347/168933256-f6648c66-5d99-464d-8843-a6d220070612.jpg)

2.  Menu Principal: 
   a. Criar logo clean com nossas iniciais.
   b. Colocar botão com o CV como no site que estamos tomando como padrão.

3. Primeira seção:
   a. Tentar replicar a forma fixa de pôr os links de redes sociais. 

4. Seção 'sobre':
  a. Incluir um a:hover alterando a nossa foto.

5. Seção sobre 'Formações': 
  a. Fazer no modelo linha do tempo. 

6. Seção experiências:
  a. Uma vez que não temos experiências penso que seria melhor destacar o que conseguimos fazer com as tecnologias que conhecemos.

7.  Footer: 
   a. Incluir os contatos mais pessoais: Tel, email, localização.
